// mottos.js
// Random mottos for the VORTEKS start screen, mixing classic gaming memes with VORTEKS-specific in-jokes

export const MOTTOS = [
  // Classic gaming memes
  "The cake is a lie... but the cards are real!",
  "Would you kindly... reshuffle your deck?",
  "All your base are belong to us",
  "A wild VORTEKS appeared!",
  "The princess is in another castle... but victory is here!",
  "Do a barrel roll with your energy management!",
  "It's dangerous to go alone! Take this deck.",
  "War. War never changes. But your hand does.",
  "Rise and shine, Mr. Freeman... time to play cards.",
  "Stay a while and listen... to your strategy",
  
  // VORTEKS-specific in-jokes and mechanics
  "Burn stacks don't lie 🔥",
  "Overheal is not a bug, it's a feature!",
  "Echo + Zap reshuffle: fixed and fabulous ✨",
  "Cat persona unlocked: maximum fluff achieved 🐱",
  "Scholar's 25% draw luck is real (we checked the math)",
  "Energy uncapping: because 6 was never enough 🔆",
  "Perfect blocks build perfect egos 🛡️",
  "Reconsider: Spend all energy. Reshuffle your deck. Profit?",
  "Pierce damage: when shields just get in the way",
  "Win streaks: harder than they look, easier than they should be",
  "Quirks: because vanilla gameplay is for vanilla people",
  "The Robot opponent is still out there... somewhere 🤖",
  "Blush + mole = instant Cat recognition protocol",
  "Turn diversity: attack, skill, power, repeat",
  "Banking energy: the art of strategic hoarding",
  "Shields at 10+: turtle power activated 🐢",
  "Burst damage: go big or go home",
  "Guardian quirk: because taking damage is so last season",
  "Minty fresh energy boosts 🔆🌿",
  "Spicy burns for spicy plays 🌶️",
  "Hearts at 1 HP: living dangerously since day one ❤️",
  "Face rerolls: because first impressions matter",
  "Unlocks modal: your trophy collection awaits 🏆",
  "Debug button: for when reality needs adjustment",
  "Presto: 1❤ for random opponent card? Totally balanced",
  "Reconsider ALL energy: the nuclear option ☢️",
  "Freeze tax: because your opponent had too much fun",
  "Wallop 👊: when you need to assert dominance",
  "Overheal to 30: because 20 HP is for cowards",
  "Minty quirk: addicted to high energy plays 💚",
  "Perfect block victory: 0 damage taken, maximum smugness",
  "Scholar quirk: card advantage is life advantage 📚",
  "Spicy quirk: burn everything, ask questions later 🔥",
  "Piercer quirk: shields are just suggestions anyway",
  "Guardian quirk: pacifist runs are valid strategies",
  "Hearty quirk: clutch HP management since v1.0",
  "MY FIRST QUIRK: extra card because we're generous",
  "Campaign booster scaling: suffering builds character",
  "Elite opponents: we heard you like Dark Souls",
  "Deck building: 30 cards of pure optimization",
  "Quick Start: for when you just want to punch things",
  "Full initialization: quirk selection is serious business",
  "Face generator: because every enemy needs personality",
  "Telemetry: we're watching your plays (for science)",
  "Achievement unlocks: gotta catch 'em all 🎯",
  "Win streak tracking: pressure makes diamonds",
  "Random opponent names: Bob the Doctor sounds legit",
  "Status effects: because vanilla combat is boring",
  "Pierce damage: armor? what armor? 🗡️",
  "VORTEKS: Unicode Card Battler extraordinaire!"
];