// mottos.js
// Random mottos for the VORTEKS start screen, mixing classic gaming memes with VORTEKS-specific in-jokes

export const MOTTOS = [
  // Classic gaming memes
  "The cake is a lie... but the cards are real!",
  "Would you kindly... reshuffle your deck?",
  "All your base are belong to us",
  "A wild VORTEKS appeared!",
  "The princess is in another castle... but victory is here!",
  "Do a barrel roll with your energy management!",
  "It's dangerous to go alone! Take this deck.",
  "War. War never changes. But your hand does.",
  "Rise and shine, Mr. Freeman... time to play cards.",
  "Stay a while and listen... to your strategy",
  
  // VORTEKS-specific in-jokes and mechanics
  "Burn stacks don't lie 🔥",
  "Overheal is not a bug, it's a feature!",
  "Echo + Zap reshuffle: fixed and fabulous ✨",
  "Cat persona unlocked: maximum fluff achieved 🐱",
  "Scholar's 25% draw luck is real (we checked the math)",
  "Energy uncapping: because 6 was never enough 🔆",
  "Perfect blocks build perfect egos 🛡️",
  "Reconsider: Spend all energy. Reshuffle your deck. Profit?",
  "Pierce damage: when shields just get in the way",
  "Win streaks: harder than they look, easier than they should be",
  "Quirks: because vanilla gameplay is for vanilla people",
  "The Robot opponent is still out there... somewhere 🤖",
  "Blush + mole = instant Cat recognition protocol",
  "Turn diversity: attack, skill, power, repeat",
  "Banking energy: the art of strategic hoarding",
  "Shields at 10+: turtle power activated 🐢",
  "Burst damage: go big or go home",
  "Guardian quirk: because taking damage is so last season",
  "Minty fresh energy boosts 🔆🌿",
  "Spicy burns for spicy plays 🌶️",
  "Hearts at 1 HP: living dangerously since day one ❤️",
  "Face rerolls: because first impressions matter",
  "Unlocks modal: your trophy collection awaits 🏆",
  "Debug button: for when reality needs adjustment",
  "Presto: 1❤ for random opponent card? Totally balanced",
  "Reconsider ALL energy: the nuclear option ☢️",
  "Freeze tax: because your opponent had too much fun",
  "Wallop 👊: when you need to assert dominance",
  "Overheal to 30: because 20 HP is for cowards",
  "Minty quirk: addicted to high energy plays 💚",
  "Perfect block victory: 0 damage taken, maximum smugness",
  "Scholar quirk: card advantage is life advantage 📚",
  "Spicy quirk: burn everything, ask questions later 🔥",
  "Piercer quirk: shields are just suggestions anyway",
  "Guardian quirk: pacifist runs are valid strategies",
  "Hearty quirk: clutch HP management since v1.0",
  "MY FIRST QUIRK: extra card because we're generous",
  "Campaign booster scaling: suffering builds character",
  "Elite opponents: we heard you like Dark Souls",
  "Deck building: 30 cards of pure optimization",
  "Quick Start: for when you just want to punch things",
  "Full initialization: quirk selection is serious business",
  "Face generator: because every enemy needs personality",
  "Telemetry: we're watching your plays (for science)",
  "Achievement unlocks: gotta catch 'em all 🎯",
  "Win streak tracking: pressure makes diamonds",
  "Random opponent names: Bob the Doctor sounds legit",
  "Status effects: because vanilla combat is boring",
  "Pierce damage: armor? what armor? 🗡️",
  "VORTEKS: Unicode Card Battler extraordinaire!",
  
  // Spiritual & Philosophical Wisdom
  "Be still and know that victory comes from within 🕊️",
  "The path of a thousand battles begins with a single card 🌸",
  "What you seek is seeking you... in your deck 🔮",
  "Every ending is a new beginning, every reshuffle a fresh start 🌱",
  "In the midst of winter, I found within me an invincible summer ❄️→☀️",
  "The wise warrior wins before the battle begins 🧘‍♂️",
  "Flow like water, strike like lightning ⚡🌊",
  "Your VORTEK reflects your inner strength 💫",
  
  // Biblical Wisdom for Gaming
  "Faith is the substance of things hoped for... like perfect draws 📜",
  "Be strong and courageous! Do not fear RNG - Deuteronomy 31:6 ⚔️",
  "In all thy ways acknowledge wisdom, and thy deck shall prosper 🙏",
  "For where your treasure is, there your heart will be also... in victory 💎",
  "The light shines in the darkness, and the darkness has not overcome it ✨",
  "Trust in strategy with all your heart - Proverbs 3:5-6 💚",
  "Iron sharpens iron, and one player sharpens another - Proverbs 27:17 🗡️",
  "All things work together for good... even bad draws - Romans 8:28 🎯",
  
  // Bhagavad Gita Gaming Wisdom
  "You have the right to perform action, but not to the fruits thereof 🍃",
  "One who sees action in inaction, and inaction in action, is wise 🧘",
  "The mind is everything. What you think you become... even in battle 🌟",
  "Change is the law of the universe... embrace the meta shift 🔄",
  "A person can rise through the efforts of their own mind ⛰️",
  "The soul is neither born, nor does it die... but VORTEKs evolve 🦋",
  "For the soul there is neither birth nor death ♾️",
  "Set thy heart upon thy work but never on its reward 💝",
  
  // I Ching Strategic Wisdom
  "The superior player adapts to circumstances ☯️",
  "Perseverance in small things leads to great accomplishments 🌱→🌳",
  "When we see the way forward, we find the strength to travel it 🛤️",
  "The wise find pleasure in water; the virtuous find pleasure in hills 🏔️💧",
  "Thunder and wind: the image of duration through movement ⚡🌪️",
  "In times of progress, the superior player remains mindful 📈🧠",
  "Return to simplicity; from simplicity, true power emerges 🎋",
  "The creative works sublime success through perseverance 🎨✨",
  
  // Zen Gaming Insights
  "Before enlightenment: shuffle deck. After enlightenment: shuffle deck 🃏",
  "The best technique is to have no technique 🌿",
  "Empty your mind, be formless, shapeless — like water 💧",
  "Do not seek to follow in the footsteps of the wise... seek what they sought 👣",
  "The present moment is the only moment available to us 🎯",
  "When you realize there is nothing lacking, the whole world belongs to you 🌍",
  "If you meet the Buddha on the battlefield... challenge him to cards 🃏😇",
  "Silence is the true teacher; strategy is the best lesson 🤫📚",
  
  // Mystical VORTEKS Wisdom
  "In the garden of consciousness, VORTEKs bloom eternal 🌺🧠",
  "Every card drawn writes destiny upon the fabric of reality 📜✨",
  "The universe shuffles itself through willing hands 🌌🙌",
  "Seek not the victory, but the victory within victory 🏆💫",
  "As above in strategy, so below in execution ⭐⬇️",
  "The VORTEK whispers secrets only the heart can understand 💝🗣️",
  "In each battle lies the seed of transcendence 🌱⚡",
  "Time is an illusion. Turns are temporary. Victory is eternal ⏰♾️",

  // New mottos for enhanced gaming wisdom 
  "Modal positioning fixed: no more UI overlap anxiety! 🎯",
  "Deck save slots: because forgetting your perfect build hurts 💾",
  "Presto card now 100% crash-free (probably) 🎩✨",
  "Three deck slots: past, present, and future perfection 🕐🕕🕘",
  "Life is like a deck builder - you need good cards and backup plans 🃏",
  "The wise player saves often, the wiser player saves smart 💡",
  "Circular references: when even your data structure gets confused 🔄😵",
  "localStorage: where dreams of perfect decks go to live forever 💭",
  "Stress testing: because Murphy's Law applies to card games too ⚡🔧",
  "Edge cases: the dark corners where bugs love to hide 🕷️",
  "Emergent errors: when features develop consciousness and rebel 🤖💥",
  "Card descriptions: finally, no more guessing what things do! 📝",
  "Quality assurance: testing today, sleeping soundly tonight 😴",
  "Bug-free code: the mythical unicorn of programming 🦄",
  "Defensive programming: paranoia that actually pays off 🛡️💰",
  "User experience: making players smile instead of rage-quit 😊",
  "Array bounds checking: because off-by-one errors aren't fashionable 📐",
  "Null reference exceptions: the 'hello world' of debugging pain 🚫💀",
  "Clean code: readable by humans, executable by machines 📚⚙️",
  "Twenty new mottos: achievement unlocked! 🏆✨"
];